trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
  displayName: 'Install SpecFlow+ LivingDoc CLI'

- script: dotnet test --filter TestCategory=SpecFlow
  displayName: 'Run SpecFlow tests'

- script: dotnet test --filter TestCategory=SmokeTests
  displayName: 'Run NUnit Selenium tests'
